package com.redhat.fiscaltax;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculoIRPF implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double faixaBase;
   private java.lang.Double aliquota;

   public CalculoIRPF()
   {
   }

   public java.lang.Double getFaixaBase()
   {
      return this.faixaBase;
   }

   public void setFaixaBase(java.lang.Double faixaBase)
   {
      this.faixaBase = faixaBase;
   }

   public java.lang.Double getAliquota()
   {
      return this.aliquota;
   }

   public void setAliquota(java.lang.Double aliquota)
   {
      this.aliquota = aliquota;
   }

   public CalculoIRPF(java.lang.Double faixaBase, java.lang.Double aliquota)
   {
      this.faixaBase = faixaBase;
      this.aliquota = aliquota;
   }

}