package com.redhat.fiscaltax;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrdemPagamentoRule implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Serviço é devido no local do prestador")
   private java.lang.Boolean servDevLocPrest;

   @org.kie.api.definition.type.Label("Retem IR")
   private java.lang.Boolean reterIR;

   @org.kie.api.definition.type.Label("Retem INSS")
   private java.lang.Boolean reterINSS;

   @org.kie.api.definition.type.Label("Unidade está estabelecida no municipio")
   private java.lang.Boolean sasEstbMunic;

   @org.kie.api.definition.type.Label("Aliquota do IRPF")
   private java.lang.Double aliquotaIRPF;

   private double saldoIRPF;

   private java.lang.Double vlIRPF = 0.0;

   @org.kie.api.definition.type.Label("Flag de ligação")
   @org.kie.api.definition.type.Description("Habilita calcular IRPF")
   private java.lang.Boolean impostopf;

   public OrdemPagamentoRule()
   {
      super();
   }

   private java.util.Date dtES;
   private java.lang.String serie;
   private java.lang.Integer idDocFiscal;
   private java.lang.String tpDocFiscal;
   private char cdTipo;
   private char tipoOperacao;
   private java.util.Date dtPagto;
   private java.util.Date dtEmissao;
   private java.lang.Integer numero;
   private java.lang.String naturezaOperacao;
   private char cancelado;
   private char descIR10;
   private java.math.BigDecimal vlUnitario;
   private java.math.BigDecimal vlTotal;
   private java.lang.Integer cdItemDocFiscal;
   private char cdClassificacao;
   private java.lang.String issNoLocal;
   private Integer cdServicoOrigem;
   private Integer cdServicoDestino;
   private Integer cdServicoLocal;
   private Integer cdServicoFederal;
   private java.lang.Integer cdMunicipio;

   private char pessoaJuridica_p;
   private java.lang.String cnpj_p;
   private java.lang.Integer cdPais_p;
   private java.lang.String uf_p;
   private java.lang.Integer cdMunicipio_p;
   private char tratamentoEspecialMunicipal;
   private java.lang.String cpf;
   private java.lang.String naturezaJuridica;
   private java.lang.Integer qtDependentes;
   private char tratamentoEspecialFederal;
   private char socUniprofissional;
   private char simplesNac;

   private char pessoaJuridica_t;
   private java.lang.String cnpj_t;
   private java.lang.Integer cdPais_t;
   private java.lang.String uf_t;
   private java.lang.Integer cdMunicipio_t;
   private java.lang.String cdAtividadeEconomica;

   public Double atualizarSaldoIRPF(Double aliquota, Double valorBase)
   {
      if (saldoIRPF > valorBase)
      {
         BigDecimal sld = new BigDecimal(saldoIRPF);
         BigDecimal vlIR = new BigDecimal(vlIRPF);
         BigDecimal al = new BigDecimal(aliquota);
         BigDecimal vl = new BigDecimal(valorBase);

         BigDecimal diferenca = sld.subtract(vl);
         BigDecimal vlAli = al.multiply(diferenca).divide(new BigDecimal(100.0));

         vlIR = vlIR.add(vlAli);
         vlIRPF = vlIR.doubleValue();
         saldoIRPF = sld.subtract(diferenca).doubleValue();
      }
      else
      {
         saldoIRPF = -1.0;
      }
      return vlIRPF;
   }

   public java.util.Date getDtES()
   {
      return dtES;
   }

   public void setDtES(java.util.Date dtES)
   {
      this.dtES = dtES;
   }

   public java.lang.String getSerie()
   {
      return serie;
   }

   public void setSerie(java.lang.String serie)
   {
      this.serie = serie;
   }

   public java.lang.Integer getIdDocFiscal()
   {
      return idDocFiscal;
   }

   public void setIdDocFiscal(java.lang.Integer idDocFiscal)
   {
      this.idDocFiscal = idDocFiscal;
   }

   public java.lang.String getTpDocFiscal()
   {
      return tpDocFiscal;
   }

   public void setTpDocFiscal(java.lang.String tpDocFiscal)
   {
      this.tpDocFiscal = tpDocFiscal;
   }

   public char getCdTipo()
   {
      return cdTipo;
   }

   public void setCdTipo(char cdTipo)
   {
      this.cdTipo = cdTipo;
   }

   public char getTipoOperacao()
   {
      return tipoOperacao;
   }

   public void setTipoOperacao(char tipoOperacao)
   {
      this.tipoOperacao = tipoOperacao;
   }

   public java.util.Date getDtPagto()
   {
      return dtPagto;
   }

   public void setDtPagto(java.util.Date dtPagto)
   {
      this.dtPagto = dtPagto;
   }

   public java.util.Date getDtEmissao()
   {
      return dtEmissao;
   }

   public void setDtEmissao(java.util.Date dtEmissao)
   {
      this.dtEmissao = dtEmissao;
   }

   public java.lang.Integer getNumero()
   {
      return numero;
   }

   public void setNumero(java.lang.Integer numero)
   {
      this.numero = numero;
   }

   public java.lang.String getNaturezaOperacao()
   {
      return naturezaOperacao;
   }

   public void setNaturezaOperacao(java.lang.String naturezaOperacao)
   {
      this.naturezaOperacao = naturezaOperacao;
   }

   public char getCancelado()
   {
      return cancelado;
   }

   public void setCancelado(char cancelado)
   {
      this.cancelado = cancelado;
   }

   public char getDescIR10()
   {
      return descIR10;
   }

   public void setDescIR10(char descIR10)
   {
      this.descIR10 = descIR10;
   }

   public java.math.BigDecimal getVlUnitario()
   {
      return vlUnitario;
   }

   public void setVlUnitario(java.math.BigDecimal vlUnitario)
   {
      this.vlUnitario = vlUnitario;
   }

   public java.math.BigDecimal getVlTotal()
   {
      return vlTotal;
   }

   public void setVlTotal(java.math.BigDecimal vlTotal)
   {
      this.vlTotal = vlTotal;
   }

   public java.lang.Integer getCdItemDocFiscal()
   {
      return cdItemDocFiscal;
   }

   public void setCdItemDocFiscal(java.lang.Integer cdItemDocFiscal)
   {
      this.cdItemDocFiscal = cdItemDocFiscal;
   }

   public char getCdClassificacao()
   {
      return cdClassificacao;
   }

   public void setCdClassificacao(char cdClassificacao)
   {
      this.cdClassificacao = cdClassificacao;
   }

   public java.lang.String getIssNoLocal()
   {
      return issNoLocal;
   }

   public void setIssNoLocal(java.lang.String issNoLocal)
   {
      this.issNoLocal = issNoLocal;
   }

   public java.lang.Integer getCdMunicipio()
   {
      return cdMunicipio;
   }

   public void setCdMunicipio(java.lang.Integer cdMunicipio)
   {
      this.cdMunicipio = cdMunicipio;
   }

   public char getPessoaJuridica_p()
   {
      return pessoaJuridica_p;
   }

   public void setPessoaJuridica_p(char pessoaJuridica_p)
   {
      this.pessoaJuridica_p = pessoaJuridica_p;
   }

   public java.lang.String getCnpj_p()
   {
      return cnpj_p;
   }

   public void setCnpj_p(java.lang.String cnpj_p)
   {
      this.cnpj_p = cnpj_p;
   }

   public java.lang.Integer getCdPais_p()
   {
      return cdPais_p;
   }

   public void setCdPais_p(java.lang.Integer cdPais_p)
   {
      this.cdPais_p = cdPais_p;
   }

   public java.lang.String getUf_p()
   {
      return uf_p;
   }

   public void setUf_p(java.lang.String uf_p)
   {
      this.uf_p = uf_p;
   }

   public java.lang.Integer getCdMunicipio_p()
   {
      return cdMunicipio_p;
   }

   public void setCdMunicipio_p(java.lang.Integer cdMunicipio_p)
   {
      this.cdMunicipio_p = cdMunicipio_p;
   }

   public char getTratamentoEspecialMunicipal()
   {
      return tratamentoEspecialMunicipal;
   }

   public void setTratamentoEspecialMunicipal(char tratamentoEspecialMunicipal)
   {
      this.tratamentoEspecialMunicipal = tratamentoEspecialMunicipal;
   }

   public java.lang.String getCpf()
   {
      return cpf;
   }

   public void setCpf(java.lang.String cpf)
   {
      this.cpf = cpf;
   }

   public java.lang.String getNaturezaJuridica()
   {
      return naturezaJuridica;
   }

   public void setNaturezaJuridica(java.lang.String naturezaJuridica)
   {
      this.naturezaJuridica = naturezaJuridica;
   }

   public java.lang.Integer getQtDependentes()
   {
      return qtDependentes;
   }

   public void setQtDependentes(java.lang.Integer qtDependentes)
   {
      this.qtDependentes = qtDependentes;
   }

   public char getTratamentoEspecialFederal()
   {
      return tratamentoEspecialFederal;
   }

   public void setTratamentoEspecialFederal(char tratamentoEspecialFederal)
   {
      this.tratamentoEspecialFederal = tratamentoEspecialFederal;
   }

   public char getSocUniprofissional()
   {
      return socUniprofissional;
   }

   public void setSocUniprofissional(char socUniprofissional)
   {
      this.socUniprofissional = socUniprofissional;
   }

   public char getSimplesNac()
   {
      return simplesNac;
   }

   public void setSimplesNac(char simplesNac)
   {
      this.simplesNac = simplesNac;
   }

   public char getPessoaJuridica_t()
   {
      return pessoaJuridica_t;
   }

   public void setPessoaJuridica_t(char pessoaJuridica_t)
   {
      this.pessoaJuridica_t = pessoaJuridica_t;
   }

   public java.lang.String getCnpj_t()
   {
      return cnpj_t;
   }

   public void setCnpj_t(java.lang.String cnpj_t)
   {
      this.cnpj_t = cnpj_t;
   }

   public java.lang.Integer getCdPais_t()
   {
      return cdPais_t;
   }

   public void setCdPais_t(java.lang.Integer cdPais_t)
   {
      this.cdPais_t = cdPais_t;
   }

   public java.lang.String getUf_t()
   {
      return uf_t;
   }

   public void setUf_t(java.lang.String uf_t)
   {
      this.uf_t = uf_t;
   }

   public java.lang.Integer getCdMunicipio_t()
   {
      return cdMunicipio_t;
   }

   public void setCdMunicipio_t(java.lang.Integer cdMunicipio_t)
   {
      this.cdMunicipio_t = cdMunicipio_t;
   }

   public java.lang.String getCdAtividadeEconomica()
   {
      return cdAtividadeEconomica;
   }

   public void setCdAtividadeEconomica(java.lang.String cdAtividadeEconomica)
   {
      this.cdAtividadeEconomica = cdAtividadeEconomica;
   }

   public java.lang.Boolean getServDevLocPrest()
   {
      return this.servDevLocPrest;
   }

   public void setServDevLocPrest(java.lang.Boolean servDevLocPrest)
   {
      this.servDevLocPrest = servDevLocPrest;
   }

   public java.lang.Boolean getReterIR()
   {
      return this.reterIR;
   }

   public void setReterIR(java.lang.Boolean reterIR)
   {
      this.reterIR = reterIR;
   }

   public java.lang.Boolean getReterINSS()
   {
      return this.reterINSS;
   }

   public void setReterINSS(java.lang.Boolean reterINSS)
   {
      this.reterINSS = reterINSS;
   }

   public java.lang.Boolean getSasEstbMunic()
   {
      return this.sasEstbMunic;
   }

   public void setSasEstbMunic(java.lang.Boolean sasEstbMunic)
   {
      this.sasEstbMunic = sasEstbMunic;
   }

   public java.lang.Integer getCdServicoDestino()
   {
      return this.cdServicoDestino;
   }

   public void setCdServicoDestino(java.lang.Integer cdServicoDestino)
   {
      this.cdServicoDestino = cdServicoDestino;
   }

   public java.lang.Integer getCdServicoLocal()
   {
      return this.cdServicoLocal;
   }

   public void setCdServicoLocal(java.lang.Integer cdServicoLocal)
   {
      this.cdServicoLocal = cdServicoLocal;
   }

   public java.lang.Integer getCdServicoFederal()
   {
      return this.cdServicoFederal;
   }

   public void setCdServicoFederal(java.lang.Integer cdServicoFederal)
   {
      this.cdServicoFederal = cdServicoFederal;
   }

   public java.lang.Integer getCdServicoOrigem()
   {
      return this.cdServicoOrigem;
   }

   public void setCdServicoOrigem(java.lang.Integer cdServicoOrigem)
   {
      this.cdServicoOrigem = cdServicoOrigem;
   }

   @Override
   public String toString()
   {
      StringBuilder builder = new StringBuilder();
      builder.append("OrdemPagamentoRule [");
      if (servDevLocPrest != null)
         builder.append("servDevLocPrest=").append(servDevLocPrest).append(", ");
      if (reterIR != null)
         builder.append("reterIR=").append(reterIR).append(", ");
      if (reterINSS != null)
         builder.append("reterINSS=").append(reterINSS).append(", ");
      if (sasEstbMunic != null)
         builder.append("sasEstbMunic=").append(sasEstbMunic).append(", ");
      if (aliquotaIRPF != null)
         builder.append("aliquotaIRPF=").append(aliquotaIRPF).append(", ");
      builder.append("saldoIRPF=").append(saldoIRPF).append(", ");
      if (vlIRPF != null)
         builder.append("vlIRPF=").append(vlIRPF).append(", ");
      if (impostopf != null)
         builder.append("impostopf=").append(impostopf).append(", ");
      if (dtES != null)
         builder.append("dtES=").append(dtES).append(", ");
      if (serie != null)
         builder.append("serie=").append(serie).append(", ");
      if (idDocFiscal != null)
         builder.append("idDocFiscal=").append(idDocFiscal).append(", ");
      if (tpDocFiscal != null)
         builder.append("tpDocFiscal=").append(tpDocFiscal).append(", ");
      builder.append("cdTipo=").append(cdTipo).append(", tipoOperacao=").append(tipoOperacao).append(", ");
      if (dtPagto != null)
         builder.append("dtPagto=").append(dtPagto).append(", ");
      if (dtEmissao != null)
         builder.append("dtEmissao=").append(dtEmissao).append(", ");
      if (numero != null)
         builder.append("numero=").append(numero).append(", ");
      if (naturezaOperacao != null)
         builder.append("naturezaOperacao=").append(naturezaOperacao).append(", ");
      builder.append("cancelado=").append(cancelado).append(", descIR10=").append(descIR10).append(", ");
      if (vlUnitario != null)
         builder.append("vlUnitario=").append(vlUnitario).append(", ");
      if (vlTotal != null)
         builder.append("vlTotal=").append(vlTotal).append(", ");
      if (cdItemDocFiscal != null)
         builder.append("cdItemDocFiscal=").append(cdItemDocFiscal).append(", ");
      builder.append("cdClassificacao=").append(cdClassificacao).append(", ");
      if (issNoLocal != null)
         builder.append("issNoLocal=").append(issNoLocal).append(", ");
      if (cdServicoOrigem != null)
         builder.append("cdServicoOrigem=").append(cdServicoOrigem).append(", ");
      if (cdServicoDestino != null)
         builder.append("cdServicoDestino=").append(cdServicoDestino).append(", ");
      if (cdServicoLocal != null)
         builder.append("cdServicoLocal=").append(cdServicoLocal).append(", ");
      if (cdServicoFederal != null)
         builder.append("cdServicoFederal=").append(cdServicoFederal).append(", ");
      if (cdMunicipio != null)
         builder.append("cdMunicipio=").append(cdMunicipio).append(", ");
      builder.append("pessoaJuridica_p=").append(pessoaJuridica_p).append(", ");
      if (cnpj_p != null)
         builder.append("cnpj_p=").append(cnpj_p).append(", ");
      if (cdPais_p != null)
         builder.append("cdPais_p=").append(cdPais_p).append(", ");
      if (uf_p != null)
         builder.append("uf_p=").append(uf_p).append(", ");
      if (cdMunicipio_p != null)
         builder.append("cdMunicipio_p=").append(cdMunicipio_p).append(", ");
      builder.append("tratamentoEspecialMunicipal=").append(tratamentoEspecialMunicipal).append(", ");
      if (cpf != null)
         builder.append("cpf=").append(cpf).append(", ");
      if (naturezaJuridica != null)
         builder.append("naturezaJuridica=").append(naturezaJuridica).append(", ");
      if (qtDependentes != null)
         builder.append("qtDependentes=").append(qtDependentes).append(", ");
      builder.append("tratamentoEspecialFederal=").append(tratamentoEspecialFederal).append(", socUniprofissional=")
            .append(socUniprofissional).append(", simplesNac=").append(simplesNac).append(", pessoaJuridica_t=")
            .append(pessoaJuridica_t).append(", ");
      if (cnpj_t != null)
         builder.append("cnpj_t=").append(cnpj_t).append(", ");
      if (cdPais_t != null)
         builder.append("cdPais_t=").append(cdPais_t).append(", ");
      if (uf_t != null)
         builder.append("uf_t=").append(uf_t).append(", ");
      if (cdMunicipio_t != null)
         builder.append("cdMunicipio_t=").append(cdMunicipio_t).append(", ");
      if (cdAtividadeEconomica != null)
         builder.append("cdAtividadeEconomica=").append(cdAtividadeEconomica);
      builder.append("]");
      return builder.toString();
   }

   public java.lang.Double getAliquotaIRPF()
   {
      return this.aliquotaIRPF;
   }

   public void setAliquotaIRPF(java.lang.Double aliquotaIRPF)
   {
      this.aliquotaIRPF = aliquotaIRPF;
   }

   public java.lang.Double getVlIRPF()
   {
      return this.vlIRPF;
   }

   public void setVlIRPF(java.lang.Double vlIRPF)
   {
      this.vlIRPF = vlIRPF;
   }

   public double getSaldoIRPF()
   {
      return this.saldoIRPF;
   }

   public void setSaldoIRPF(double saldoIRPF)
   {
      this.saldoIRPF = saldoIRPF;
   }

   public java.lang.Boolean getImpostopf()
   {
      return this.impostopf;
   }

   public void setImpostopf(java.lang.Boolean impostopf)
   {
      this.impostopf = impostopf;
   }

   public OrdemPagamentoRule(java.lang.Boolean servDevLocPrest,
         java.lang.Boolean reterIR, java.lang.Boolean reterINSS,
         java.lang.Boolean sasEstbMunic, java.lang.Double aliquotaIRPF,
         double saldoIRPF, java.lang.Double vlIRPF, java.lang.Boolean impostopf,
         java.util.Date dtES, java.lang.String serie,
         java.lang.Integer idDocFiscal, java.lang.String tpDocFiscal,
         char cdTipo, char tipoOperacao, java.util.Date dtPagto,
         java.util.Date dtEmissao, java.lang.Integer numero,
         java.lang.String naturezaOperacao, char cancelado, char descIR10,
         java.math.BigDecimal vlUnitario, java.math.BigDecimal vlTotal,
         java.lang.Integer cdItemDocFiscal, char cdClassificacao,
         java.lang.String issNoLocal, java.lang.Integer cdServicoOrigem,
         java.lang.Integer cdServicoDestino, java.lang.Integer cdServicoLocal,
         java.lang.Integer cdServicoFederal, java.lang.Integer cdMunicipio,
         char pessoaJuridica_p, java.lang.String cnpj_p,
         java.lang.Integer cdPais_p, java.lang.String uf_p,
         java.lang.Integer cdMunicipio_p, char tratamentoEspecialMunicipal,
         java.lang.String cpf, java.lang.String naturezaJuridica,
         java.lang.Integer qtDependentes, char tratamentoEspecialFederal,
         char socUniprofissional, char simplesNac, char pessoaJuridica_t,
         java.lang.String cnpj_t, java.lang.Integer cdPais_t,
         java.lang.String uf_t, java.lang.Integer cdMunicipio_t,
         java.lang.String cdAtividadeEconomica)
   {
      this.servDevLocPrest = servDevLocPrest;
      this.reterIR = reterIR;
      this.reterINSS = reterINSS;
      this.sasEstbMunic = sasEstbMunic;
      this.aliquotaIRPF = aliquotaIRPF;
      this.saldoIRPF = saldoIRPF;
      this.vlIRPF = vlIRPF;
      this.impostopf = impostopf;
      this.dtES = dtES;
      this.serie = serie;
      this.idDocFiscal = idDocFiscal;
      this.tpDocFiscal = tpDocFiscal;
      this.cdTipo = cdTipo;
      this.tipoOperacao = tipoOperacao;
      this.dtPagto = dtPagto;
      this.dtEmissao = dtEmissao;
      this.numero = numero;
      this.naturezaOperacao = naturezaOperacao;
      this.cancelado = cancelado;
      this.descIR10 = descIR10;
      this.vlUnitario = vlUnitario;
      this.vlTotal = vlTotal;
      this.cdItemDocFiscal = cdItemDocFiscal;
      this.cdClassificacao = cdClassificacao;
      this.issNoLocal = issNoLocal;
      this.cdServicoOrigem = cdServicoOrigem;
      this.cdServicoDestino = cdServicoDestino;
      this.cdServicoLocal = cdServicoLocal;
      this.cdServicoFederal = cdServicoFederal;
      this.cdMunicipio = cdMunicipio;
      this.pessoaJuridica_p = pessoaJuridica_p;
      this.cnpj_p = cnpj_p;
      this.cdPais_p = cdPais_p;
      this.uf_p = uf_p;
      this.cdMunicipio_p = cdMunicipio_p;
      this.tratamentoEspecialMunicipal = tratamentoEspecialMunicipal;
      this.cpf = cpf;
      this.naturezaJuridica = naturezaJuridica;
      this.qtDependentes = qtDependentes;
      this.tratamentoEspecialFederal = tratamentoEspecialFederal;
      this.socUniprofissional = socUniprofissional;
      this.simplesNac = simplesNac;
      this.pessoaJuridica_t = pessoaJuridica_t;
      this.cnpj_t = cnpj_t;
      this.cdPais_t = cdPais_t;
      this.uf_t = uf_t;
      this.cdMunicipio_t = cdMunicipio_t;
      this.cdAtividadeEconomica = cdAtividadeEconomica;
   }

}