package com.redhat.fiscaltax;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrdemPagamentoEntrada implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer acao;
   private java.lang.Integer CIA;
   @org.kie.api.definition.type.Label("CPF ou CNPJ")
   private java.lang.String documento;
   @org.kie.api.definition.type.Label("Indicador de pessoa física ou jurídica")
   private java.lang.String FJ;
   @org.kie.api.definition.type.Label("Código do municipio")
   private java.lang.String codMunic;
   @org.kie.api.definition.type.Label("Nome do Municipio")
   private java.lang.String nmMunicipio;
   private java.lang.String pais;
   private java.lang.Integer personJur;
   private java.lang.Integer qtdDep;
   private java.lang.String Isen_IR;
   private java.lang.String Isen_INSS;
   private java.lang.String Isen_PIS;
   private java.lang.String Isen_COFINS;
   private java.lang.String Isen_CSLL;
   private java.lang.String Isen_ISS;
   private java.lang.String Isen_SEST;
   private java.lang.String Isen_SENAT;
   private String Incent_IR;
   private String Incent_INSS;
   private String Incent_PIS;
   private String Incent_COFINS;
   private String Incent_CSLL;
   private String Incent_ISS;
   private String Incent_SEST;
   private String Incent_SENAT;
   @org.kie.api.definition.type.Label("Serie")
   private java.lang.String serie;
   private java.lang.Integer numNota;
   private java.lang.String tpDocFiscal;
   private java.util.Date dtEmissao;
   private java.util.Date dtEntrada;
   private java.util.Date dtPagto;
   private java.lang.Integer qtdItem;
   private java.lang.Integer numItem;
   private java.lang.Integer codMunicServ;
   private java.lang.String nmMunicServ;
   private char classif;
   private java.lang.String cdServico;
   private java.lang.String dscServico;
   private java.lang.String vlPensao;
   private Double vlEncAlimentacao;
   private Double vlEncTransporte;
   private Double vlMatServ;
   private Double vlItem;

   public java.lang.Integer getAcao()
   {
      return acao;
   }

   public void setAcao(java.lang.Integer acao)
   {
      this.acao = acao;
   }

   public java.lang.Integer getCIA()
   {
      return CIA;
   }

   public void setCIA(java.lang.Integer cIA)
   {
      CIA = cIA;
   }

   public java.lang.String getDocumento()
   {
      return documento;
   }

   public void setDocumento(java.lang.String documento)
   {
      this.documento = documento;
   }

   public java.lang.String getFJ()
   {
      return FJ;
   }

   public void setFJ(java.lang.String fJ)
   {
      FJ = fJ;
   }

   public java.lang.String getCodMunic()
   {
      return codMunic;
   }

   public void setCodMunic(java.lang.String codMunic)
   {
      this.codMunic = codMunic;
   }

   public java.lang.String getNmMunicipio()
   {
      return nmMunicipio;
   }

   public void setNmMunicipio(java.lang.String nmMunicipio)
   {
      this.nmMunicipio = nmMunicipio;
   }

   public java.lang.String getPais()
   {
      return pais;
   }

   public void setPais(java.lang.String pais)
   {
      this.pais = pais;
   }

   public java.lang.Integer getPersonJur()
   {
      return personJur;
   }

   public void setPersonJur(java.lang.Integer personJur)
   {
      this.personJur = personJur;
   }

   public java.lang.Integer getQtdDep()
   {
      return qtdDep;
   }

   public void setQtdDep(java.lang.Integer qtdDep)
   {
      this.qtdDep = qtdDep;
   }

   public java.lang.String getIsen_IR()
   {
      return Isen_IR;
   }

   public void setIsen_IR(java.lang.String isen_IR)
   {
      Isen_IR = isen_IR;
   }

   public java.lang.String getIsen_INSS()
   {
      return Isen_INSS;
   }

   public void setIsen_INSS(java.lang.String isen_INSS)
   {
      Isen_INSS = isen_INSS;
   }

   public java.lang.String getIsen_PIS()
   {
      return Isen_PIS;
   }

   public void setIsen_PIS(java.lang.String isen_PIS)
   {
      Isen_PIS = isen_PIS;
   }

   public java.lang.String getIsen_COFINS()
   {
      return Isen_COFINS;
   }

   public void setIsen_COFINS(java.lang.String isen_COFINS)
   {
      Isen_COFINS = isen_COFINS;
   }

   public java.lang.String getIsen_CSLL()
   {
      return Isen_CSLL;
   }

   public void setIsen_CSLL(java.lang.String isen_CSLL)
   {
      Isen_CSLL = isen_CSLL;
   }

   public java.lang.String getIsen_ISS()
   {
      return Isen_ISS;
   }

   public void setIsen_ISS(java.lang.String isen_ISS)
   {
      Isen_ISS = isen_ISS;
   }

   public java.lang.String getIsen_SEST()
   {
      return Isen_SEST;
   }

   public void setIsen_SEST(java.lang.String isen_SEST)
   {
      Isen_SEST = isen_SEST;
   }

   public java.lang.String getIsen_SENAT()
   {
      return Isen_SENAT;
   }

   public void setIsen_SENAT(java.lang.String isen_SENAT)
   {
      Isen_SENAT = isen_SENAT;
   }

   public java.lang.String getSerie()
   {
      return serie;
   }

   public void setSerie(java.lang.String serie)
   {
      this.serie = serie;
   }

   public java.lang.Integer getNumNota()
   {
      return numNota;
   }

   public void setNumNota(java.lang.Integer numNota)
   {
      this.numNota = numNota;
   }

   public java.lang.String getTpDocFiscal()
   {
      return tpDocFiscal;
   }

   public void setTpDocFiscal(java.lang.String tpDocFiscal)
   {
      this.tpDocFiscal = tpDocFiscal;
   }

   public java.util.Date getDtEmissao()
   {
      return dtEmissao;
   }

   public void setDtEmissao(java.util.Date dtEmissao)
   {
      this.dtEmissao = dtEmissao;
   }

   public java.util.Date getDtEntrada()
   {
      return dtEntrada;
   }

   public void setDtEntrada(java.util.Date dtEntrada)
   {
      this.dtEntrada = dtEntrada;
   }

   public java.util.Date getDtPagto()
   {
      return dtPagto;
   }

   public void setDtPagto(java.util.Date dtPagto)
   {
      this.dtPagto = dtPagto;
   }

   public java.lang.Integer getQtdItem()
   {
      return qtdItem;
   }

   public void setQtdItem(java.lang.Integer qtdItem)
   {
      this.qtdItem = qtdItem;
   }

   public java.lang.Integer getNumItem()
   {
      return numItem;
   }

   public void setNumItem(java.lang.Integer numItem)
   {
      this.numItem = numItem;
   }

   public java.lang.Integer getCodMunicServ()
   {
      return codMunicServ;
   }

   public void setCodMunicServ(java.lang.Integer codMunicServ)
   {
      this.codMunicServ = codMunicServ;
   }

   public java.lang.String getNmMunicServ()
   {
      return nmMunicServ;
   }

   public void setNmMunicServ(java.lang.String nmMunicServ)
   {
      this.nmMunicServ = nmMunicServ;
   }

   public char getClassif()
   {
      return classif;
   }

   public void setClassif(char classif)
   {
      this.classif = classif;
   }

   public java.lang.String getCdServico()
   {
      return cdServico;
   }

   public void setCdServico(java.lang.String cdServico)
   {
      this.cdServico = cdServico;
   }

   public java.lang.String getDscServico()
   {
      return dscServico;
   }

   public void setDscServico(java.lang.String dscServico)
   {
      this.dscServico = dscServico;
   }

   public java.lang.String getVlPensao()
   {
      return vlPensao;
   }

   public void setVlPensao(java.lang.String vlPensao)
   {
      this.vlPensao = vlPensao;
   }

   public OrdemPagamentoEntrada()
   {
   }

   public java.lang.String getIncent_IR()
   {
      return this.Incent_IR;
   }

   public void setIncent_IR(java.lang.String Incent_IR)
   {
      this.Incent_IR = Incent_IR;
   }

   public java.lang.String getIncent_INSS()
   {
      return this.Incent_INSS;
   }

   public void setIncent_INSS(java.lang.String Incent_INSS)
   {
      this.Incent_INSS = Incent_INSS;
   }

   public java.lang.String getIncent_PIS()
   {
      return this.Incent_PIS;
   }

   public void setIncent_PIS(java.lang.String Incent_PIS)
   {
      this.Incent_PIS = Incent_PIS;
   }

   public java.lang.String getIncent_COFINS()
   {
      return this.Incent_COFINS;
   }

   public void setIncent_COFINS(java.lang.String Incent_COFINS)
   {
      this.Incent_COFINS = Incent_COFINS;
   }

   public java.lang.String getIncent_CSLL()
   {
      return this.Incent_CSLL;
   }

   public void setIncent_CSLL(java.lang.String Incent_CSLL)
   {
      this.Incent_CSLL = Incent_CSLL;
   }

   public java.lang.String getIncent_ISS()
   {
      return this.Incent_ISS;
   }

   public void setIncent_ISS(java.lang.String Incent_ISS)
   {
      this.Incent_ISS = Incent_ISS;
   }

   public java.lang.String getIncent_SEST()
   {
      return this.Incent_SEST;
   }

   public void setIncent_SEST(java.lang.String Incent_SEST)
   {
      this.Incent_SEST = Incent_SEST;
   }

   public java.lang.String getIncent_SENAT()
   {
      return this.Incent_SENAT;
   }

   public void setIncent_SENAT(java.lang.String Incent_SENAT)
   {
      this.Incent_SENAT = Incent_SENAT;
   }

   public java.lang.Double getVlEncAlimentacao()
   {
      return this.vlEncAlimentacao;
   }

   public void setVlEncAlimentacao(java.lang.Double vlEncAlimentacao)
   {
      this.vlEncAlimentacao = vlEncAlimentacao;
   }

   public java.lang.Double getVlEncTransporte()
   {
      return this.vlEncTransporte;
   }

   public void setVlEncTransporte(java.lang.Double vlEncTransporte)
   {
      this.vlEncTransporte = vlEncTransporte;
   }

   public java.lang.Double getVlMatServ()
   {
      return this.vlMatServ;
   }

   public void setVlMatServ(java.lang.Double vlMatServ)
   {
      this.vlMatServ = vlMatServ;
   }

   public java.lang.Double getVlItem()
   {
      return this.vlItem;
   }

   public void setVlItem(java.lang.Double vlItem)
   {
      this.vlItem = vlItem;
   }

   public OrdemPagamentoEntrada(java.lang.Integer acao, java.lang.Integer CIA,
         java.lang.String documento, java.lang.String FJ,
         java.lang.String codMunic, java.lang.String nmMunicipio,
         java.lang.String pais, java.lang.Integer personJur,
         java.lang.Integer qtdDep, java.lang.String Isen_IR,
         java.lang.String Isen_INSS, java.lang.String Isen_PIS,
         java.lang.String Isen_COFINS, java.lang.String Isen_CSLL,
         java.lang.String Isen_ISS, java.lang.String Isen_SEST,
         java.lang.String Isen_SENAT, java.lang.String Incent_IR,
         java.lang.String Incent_INSS, java.lang.String Incent_PIS,
         java.lang.String Incent_COFINS, java.lang.String Incent_CSLL,
         java.lang.String Incent_ISS, java.lang.String Incent_SEST,
         java.lang.String Incent_SENAT, java.lang.String serie,
         java.lang.Integer numNota, java.lang.String tpDocFiscal,
         java.util.Date dtEmissao, java.util.Date dtEntrada,
         java.util.Date dtPagto, java.lang.Integer qtdItem,
         java.lang.Integer numItem, java.lang.Integer codMunicServ,
         java.lang.String nmMunicServ, char classif, java.lang.String cdServico,
         java.lang.String dscServico, java.lang.String vlPensao,
         java.lang.Double vlEncAlimentacao, java.lang.Double vlEncTransporte,
         java.lang.Double vlMatServ, java.lang.Double vlItem)
   {
      this.acao = acao;
      this.CIA = CIA;
      this.documento = documento;
      this.FJ = FJ;
      this.codMunic = codMunic;
      this.nmMunicipio = nmMunicipio;
      this.pais = pais;
      this.personJur = personJur;
      this.qtdDep = qtdDep;
      this.Isen_IR = Isen_IR;
      this.Isen_INSS = Isen_INSS;
      this.Isen_PIS = Isen_PIS;
      this.Isen_COFINS = Isen_COFINS;
      this.Isen_CSLL = Isen_CSLL;
      this.Isen_ISS = Isen_ISS;
      this.Isen_SEST = Isen_SEST;
      this.Isen_SENAT = Isen_SENAT;
      this.Incent_IR = Incent_IR;
      this.Incent_INSS = Incent_INSS;
      this.Incent_PIS = Incent_PIS;
      this.Incent_COFINS = Incent_COFINS;
      this.Incent_CSLL = Incent_CSLL;
      this.Incent_ISS = Incent_ISS;
      this.Incent_SEST = Incent_SEST;
      this.Incent_SENAT = Incent_SENAT;
      this.serie = serie;
      this.numNota = numNota;
      this.tpDocFiscal = tpDocFiscal;
      this.dtEmissao = dtEmissao;
      this.dtEntrada = dtEntrada;
      this.dtPagto = dtPagto;
      this.qtdItem = qtdItem;
      this.numItem = numItem;
      this.codMunicServ = codMunicServ;
      this.nmMunicServ = nmMunicServ;
      this.classif = classif;
      this.cdServico = cdServico;
      this.dscServico = dscServico;
      this.vlPensao = vlPensao;
      this.vlEncAlimentacao = vlEncAlimentacao;
      this.vlEncTransporte = vlEncTransporte;
      this.vlMatServ = vlMatServ;
      this.vlItem = vlItem;
   }

@Override
public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("OrdemPagamentoEntrada [");
	if (acao != null)
		builder.append("acao=").append(acao).append(", ");
	if (CIA != null)
		builder.append("CIA=").append(CIA).append(", ");
	if (documento != null)
		builder.append("documento=").append(documento).append(", ");
	if (FJ != null)
		builder.append("FJ=").append(FJ).append(", ");
	if (codMunic != null)
		builder.append("codMunic=").append(codMunic).append(", ");
	if (nmMunicipio != null)
		builder.append("nmMunicipio=").append(nmMunicipio).append(", ");
	if (pais != null)
		builder.append("pais=").append(pais).append(", ");
	if (personJur != null)
		builder.append("personJur=").append(personJur).append(", ");
	if (qtdDep != null)
		builder.append("qtdDep=").append(qtdDep).append(", ");
	if (Isen_IR != null)
		builder.append("Isen_IR=").append(Isen_IR).append(", ");
	if (Isen_INSS != null)
		builder.append("Isen_INSS=").append(Isen_INSS).append(", ");
	if (Isen_PIS != null)
		builder.append("Isen_PIS=").append(Isen_PIS).append(", ");
	if (Isen_COFINS != null)
		builder.append("Isen_COFINS=").append(Isen_COFINS).append(", ");
	if (Isen_CSLL != null)
		builder.append("Isen_CSLL=").append(Isen_CSLL).append(", ");
	if (Isen_ISS != null)
		builder.append("Isen_ISS=").append(Isen_ISS).append(", ");
	if (Isen_SEST != null)
		builder.append("Isen_SEST=").append(Isen_SEST).append(", ");
	if (Isen_SENAT != null)
		builder.append("Isen_SENAT=").append(Isen_SENAT).append(", ");
	if (Incent_IR != null)
		builder.append("Incent_IR=").append(Incent_IR).append(", ");
	if (Incent_INSS != null)
		builder.append("Incent_INSS=").append(Incent_INSS).append(", ");
	if (Incent_PIS != null)
		builder.append("Incent_PIS=").append(Incent_PIS).append(", ");
	if (Incent_COFINS != null)
		builder.append("Incent_COFINS=").append(Incent_COFINS).append(", ");
	if (Incent_CSLL != null)
		builder.append("Incent_CSLL=").append(Incent_CSLL).append(", ");
	if (Incent_ISS != null)
		builder.append("Incent_ISS=").append(Incent_ISS).append(", ");
	if (Incent_SEST != null)
		builder.append("Incent_SEST=").append(Incent_SEST).append(", ");
	if (Incent_SENAT != null)
		builder.append("Incent_SENAT=").append(Incent_SENAT).append(", ");
	if (serie != null)
		builder.append("serie=").append(serie).append(", ");
	if (numNota != null)
		builder.append("numNota=").append(numNota).append(", ");
	if (tpDocFiscal != null)
		builder.append("tpDocFiscal=").append(tpDocFiscal).append(", ");
	if (dtEmissao != null)
		builder.append("dtEmissao=").append(dtEmissao).append(", ");
	if (dtEntrada != null)
		builder.append("dtEntrada=").append(dtEntrada).append(", ");
	if (dtPagto != null)
		builder.append("dtPagto=").append(dtPagto).append(", ");
	if (qtdItem != null)
		builder.append("qtdItem=").append(qtdItem).append(", ");
	if (numItem != null)
		builder.append("numItem=").append(numItem).append(", ");
	if (codMunicServ != null)
		builder.append("codMunicServ=").append(codMunicServ).append(", ");
	if (nmMunicServ != null)
		builder.append("nmMunicServ=").append(nmMunicServ).append(", ");
	builder.append("classif=").append(classif).append(", ");
	if (cdServico != null)
		builder.append("cdServico=").append(cdServico).append(", ");
	if (dscServico != null)
		builder.append("dscServico=").append(dscServico).append(", ");
	if (vlPensao != null)
		builder.append("vlPensao=").append(vlPensao).append(", ");
	if (vlEncAlimentacao != null)
		builder.append("vlEncAlimentacao=").append(vlEncAlimentacao).append(", ");
	if (vlEncTransporte != null)
		builder.append("vlEncTransporte=").append(vlEncTransporte).append(", ");
	if (vlMatServ != null)
		builder.append("vlMatServ=").append(vlMatServ).append(", ");
	if (vlItem != null)
		builder.append("vlItem=").append(vlItem);
	builder.append("]");
	return builder.toString();
}

}