package com.redhat.fiscaltax;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Retorno implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String indLocalISS;
   private Double aliquotaISS;
   @org.kie.api.definition.type.Label("Valor base IR")
   private Double vlBaseIR;

   @org.kie.api.definition.type.Label("Valor do imposto IR")
   private Double vlImpostoIR;

   @org.kie.api.definition.type.Label("Valor base INSS")
   private Double vlBaseINSS;

   @org.kie.api.definition.type.Label("Valor do imposto INSS")
   private Double vlImpostoINSS;

   @org.kie.api.definition.type.Label("Valor base ISS")
   private Double vlBaseISS;

   @org.kie.api.definition.type.Label("Valor imposto ISS")
   private Double vlImpostoISS;

   @org.kie.api.definition.type.Label("Valor base do PIS")
   private Double vlBasePIS;

   @org.kie.api.definition.type.Label("Valor imposto PIS")
   private Double vlImpostoPIS;

   @org.kie.api.definition.type.Label("Valor base COFINS")
   private Double vlBaseCOFINS;

   @org.kie.api.definition.type.Label("Valor do imposto COFINS")
   private Double vlImpostoCOFINS;

   @org.kie.api.definition.type.Label("Valor base CSLL")
   private Double vlBaseCSLL;

   @org.kie.api.definition.type.Label("Valor imposto CSLL")
   private Double vlImpostoCSLL;

   @org.kie.api.definition.type.Label("Amparos")
   private java.util.List<java.lang.String> amparos = new java.util.ArrayList();

   @org.kie.api.definition.type.Label(value = "Aliquota IR")
   private java.lang.Double aliquotaIR = 0.0;

   public Retorno()
   {
   }

   public void adicionarAmparo(String pAmp)
   {
      this.amparos.add(pAmp);
   }

   public java.util.List<java.lang.String> getAmparos()
   {
      return this.amparos;
   }

   public void setAmparos(java.util.List<java.lang.String> amparos)
   {
      this.amparos = amparos;
   }

   public java.lang.Double getAliquotaISS()
   {
      return this.aliquotaISS;
   }

   public void setAliquotaISS(java.lang.Double aliquotaISS)
   {
      this.aliquotaISS = aliquotaISS;
   }

   public java.lang.Double getVlBaseIR()
   {
      return this.vlBaseIR;
   }

   public void setVlBaseIR(java.lang.Double vlBaseIR)
   {
      this.vlBaseIR = vlBaseIR;
   }

   public java.lang.Double getVlImpostoIR()
   {
      return this.vlImpostoIR;
   }

   public void setVlImpostoIR(java.lang.Double vlImpostoIR)
   {
      this.vlImpostoIR = vlImpostoIR;
      if (this.vlImpostoIR!=null && this.vlImpostoIR>0.0 && this.vlBaseIR!=null && this.vlBaseIR>0.0){
          this.aliquotaIR = ((this.vlImpostoIR * 100)/this.vlBaseIR);
      }
   }

   public java.lang.Double getVlBaseINSS()
   {
      return this.vlBaseINSS;
   }

   public void setVlBaseINSS(java.lang.Double vlBaseINSS)
   {
      this.vlBaseINSS = vlBaseINSS;
   }

   public java.lang.Double getVlImpostoINSS()
   {
      return this.vlImpostoINSS;
   }

   public void setVlImpostoINSS(java.lang.Double vlImpostoINSS)
   {
      this.vlImpostoINSS = vlImpostoINSS;
   }

   public java.lang.Double getVlBaseISS()
   {
      return this.vlBaseISS;
   }

   public void setVlBaseISS(java.lang.Double vlBaseISS)
   {
      this.vlBaseISS = vlBaseISS;
   }

   public java.lang.Double getVlImpostoISS()
   {
      return this.vlImpostoISS;
   }

   public void setVlImpostoISS(java.lang.Double vlImpostoISS)
   {
      this.vlImpostoISS = vlImpostoISS;
   }

   public java.lang.Double getVlBasePIS()
   {
      return this.vlBasePIS;
   }

   public void setVlBasePIS(java.lang.Double vlBasePIS)
   {
      this.vlBasePIS = vlBasePIS;
   }

   public java.lang.Double getVlImpostoPIS()
   {
      return this.vlImpostoPIS;
   }

   public void setVlImpostoPIS(java.lang.Double vlImpostoPIS)
   {
      this.vlImpostoPIS = vlImpostoPIS;
   }

   public java.lang.Double getVlBaseCOFINS()
   {
      return this.vlBaseCOFINS;
   }

   public void setVlBaseCOFINS(java.lang.Double vlBaseCOFINS)
   {
      this.vlBaseCOFINS = vlBaseCOFINS;
   }

   public java.lang.Double getVlImpostoCOFINS()
   {
      return this.vlImpostoCOFINS;
   }

   public void setVlImpostoCOFINS(java.lang.Double vlImpostoCOFINS)
   {
      this.vlImpostoCOFINS = vlImpostoCOFINS;
   }

   public java.lang.Double getVlBaseCSLL()
   {
      return this.vlBaseCSLL;
   }

   public void setVlBaseCSLL(java.lang.Double vlBaseCSLL)
   {
      this.vlBaseCSLL = vlBaseCSLL;
   }

   public java.lang.Double getVlImpostoCSLL()
   {
      return this.vlImpostoCSLL;
   }

   public void setVlImpostoCSLL(java.lang.Double vlImpostoCSLL)
   {
      this.vlImpostoCSLL = vlImpostoCSLL;
   }

   @Override
   public String toString()
   {
      final int maxLen = 10;
      StringBuilder builder = new StringBuilder();
      builder.append("Retorno [");
      if (indLocalISS != null)
         builder.append("indLocalISS=").append(indLocalISS).append(", ");
      if (aliquotaISS != null)
         builder.append("aliquotaISS=").append(aliquotaISS).append(", ");
      if (vlBaseIR != null)
         builder.append("vlBaseIR=").append(vlBaseIR).append(", ");
      if (vlImpostoIR != null)
         builder.append("vlImpostoIR=").append(vlImpostoIR).append(", ");
      if (vlBaseINSS != null)
         builder.append("vlBaseINSS=").append(vlBaseINSS).append(", ");
      if (vlImpostoINSS != null)
         builder.append("vlImpostoINSS=").append(vlImpostoINSS).append(", ");
      if (vlBaseISS != null)
         builder.append("vlBaseISS=").append(vlBaseISS).append(", ");
      if (vlImpostoISS != null)
         builder.append("vlImpostoISS=").append(vlImpostoISS).append(", ");
      if (vlBasePIS != null)
         builder.append("vlBasePIS=").append(vlBasePIS).append(", ");
      if (vlImpostoPIS != null)
         builder.append("vlImpostoPIS=").append(vlImpostoPIS).append(", ");
      if (vlBaseCOFINS != null)
         builder.append("vlBaseCOFINS=").append(vlBaseCOFINS).append(", ");
      if (vlImpostoCOFINS != null)
         builder.append("vlImpostoCOFINS=").append(vlImpostoCOFINS).append(", ");
      if (vlBaseCSLL != null)
         builder.append("vlBaseCSLL=").append(vlBaseCSLL).append(", ");
      if (vlImpostoCSLL != null)
         builder.append("vlImpostoCSLL=").append(vlImpostoCSLL).append(", ");
      if (amparos != null)
         builder.append("amparos=").append(amparos.subList(0, Math.min(amparos.size(), maxLen)));
      builder.append("]");
      return builder.toString();
   }

   public java.lang.String getIndLocalISS()
   {
      return this.indLocalISS;
   }

   public void setIndLocalISS(java.lang.String indLocalISS)
   {
      this.indLocalISS = indLocalISS;
   }

   public java.lang.Double getAliquotaIR()
   {
      return this.aliquotaIR;
   }

   public void setAliquotaIR(java.lang.Double aliquotaIR)
   {
      this.aliquotaIR = aliquotaIR;
   }

   public Retorno(java.lang.String indLocalISS, java.lang.Double aliquotaISS,
         java.lang.Double vlBaseIR, java.lang.Double vlImpostoIR,
         java.lang.Double vlBaseINSS, java.lang.Double vlImpostoINSS,
         java.lang.Double vlBaseISS, java.lang.Double vlImpostoISS,
         java.lang.Double vlBasePIS, java.lang.Double vlImpostoPIS,
         java.lang.Double vlBaseCOFINS, java.lang.Double vlImpostoCOFINS,
         java.lang.Double vlBaseCSLL, java.lang.Double vlImpostoCSLL,
         java.util.List<java.lang.String> amparos, java.lang.Double aliquotaIR)
   {
      this.indLocalISS = indLocalISS;
      this.aliquotaISS = aliquotaISS;
      this.vlBaseIR = vlBaseIR;
      this.vlImpostoIR = vlImpostoIR;
      this.vlBaseINSS = vlBaseINSS;
      this.vlImpostoINSS = vlImpostoINSS;
      this.vlBaseISS = vlBaseISS;
      this.vlImpostoISS = vlImpostoISS;
      this.vlBasePIS = vlBasePIS;
      this.vlImpostoPIS = vlImpostoPIS;
      this.vlBaseCOFINS = vlBaseCOFINS;
      this.vlImpostoCOFINS = vlImpostoCOFINS;
      this.vlBaseCSLL = vlBaseCSLL;
      this.vlImpostoCSLL = vlImpostoCSLL;
      this.amparos = amparos;
      this.aliquotaIR = aliquotaIR;
   }

}